# 文件名: iac-cloudbuild.yaml (使用 volumes 确保状态共享)
options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1. Terraform 初期化 (Init)
- name: 'hashicorp/terraform:latest'
  id: 'Terraform Init'
  args:
    - '-chdir=environments/${_ENV_NAME}'
    - 'init'
    - '-backend-config=bucket=${_TF_STATE_BUCKET}'
    - '-backend-config=prefix=${_ENV_NAME}'
    - '-upgrade' 
  # ⭐️ 关键修改：定义一个卷，用于持久化 .terraform 目录
  volumes:
    - name: 'tf-data'
      path: '/root/.terraform'

# 2. Terraform 構文検証 (Validate)
- name: 'hashicorp/terraform:latest'
  id: 'Terraform Validate'
  args:
    - '-chdir=environments/${_ENV_NAME}'
    - 'validate'
  # ⭐️ 关键修改：挂载相同的卷，确保访问到 Init 结果
  volumes:
    - name: 'tf-data'
      path: '/root/.terraform'

# 3. Terraform プラン (Plan)
- name: 'hashicorp/terraform:latest'
  id: 'Terraform Plan'
  args:
    - '-chdir=environments/${_ENV_NAME}'
    - 'plan'
    - '-out=/workspace/tfplan'
    - '-input=false'
  # ⭐️ 关键修改：挂载相同的卷
  volumes:
    - name: 'tf-data'
      path: '/root/.terraform'

# 4. Terraform 適用 (Apply)
- name: 'hashicorp/terraform:latest'
  id: 'Terraform Apply'
  args:
    - '-chdir=environments/${_ENV_NAME}'
    - 'apply'
    - '-auto-approve'
    - '/workspace/tfplan'
  # ⭐️ 关键修改：挂载相同的卷
  volumes:
    - name: 'tf-data'
      path: '/root/.terraform'
      
timeout: 1800s
