# 文件名: iac-cloudbuild.yaml (使用 volumes 确保状态共享)
options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 0. 转运镜像（即便 GCR 已有，再次 push 也无害）
- name: 'gcr.io/cloud-builders/docker'
  id: 'mirror-image'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull quay.io/oauth2-proxy/oauth2-proxy:v7.13.0 || exit 1
      docker tag quay.io/oauth2-proxy/oauth2-proxy:v7.13.0 gcr.io/${PROJECT_ID}/oauth2-proxy:v7.13.0
      docker push gcr.io/${PROJECT_ID}/oauth2-proxy:v7.13.0
# 1. Terraform 初期化 (Init)
- name: 'hashicorp/terraform:latest'
  id: 'Terraform Init'
  args:
    - '-chdir=environments/${_ENV_NAME}'
    - 'init'
    - '-backend-config=bucket=${_TF_STATE_BUCKET}'
    - '-backend-config=prefix=${_ENV_NAME}'
    - '-upgrade' 
  volumes:
    - name: 'tf-data'
      path: '/root/.terraform'

# 2. Terraform 構文検証 (Validate)
- name: 'hashicorp/terraform:latest'
  id: 'Terraform Validate'
  args:
    - '-chdir=environments/${_ENV_NAME}'
    - 'validate'
  volumes:
    - name: 'tf-data'
      path: '/root/.terraform'

# 3. Terraform プラン (Plan)
- name: 'hashicorp/terraform:latest'
  id: 'Terraform Plan'
  args:
    - '-chdir=environments/${_ENV_NAME}'
    - 'plan'
    - '-out=/workspace/tfplan'
    - '-input=false'
  env:
    - 'TF_VAR_enable_ops_nat=${_ENABLE_OPS_NAT}'
  volumes:
    - name: 'tf-data'
      path: '/root/.terraform'

# 4. Terraform 適用 (Apply)
- name: 'hashicorp/terraform:latest'
  id: 'Terraform Apply'
  args:
    - '-chdir=environments/${_ENV_NAME}'
    - 'apply'
    - '-auto-approve'
    - '/workspace/tfplan'
  volumes:
    - name: 'tf-data'
      path: '/root/.terraform'

# 5. PG Client install
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ "${_ENABLE_OPS_NAT}" = "true" ]; then
        echo "检测到 NAT 已开启，开始自动化安装工具..."
        
        # 重试循环，确保 SSH 服务已启动
        for i in {1..10}; do
          gcloud compute ssh ops-vm-${_ENV_NAME} \
            --tunnel-through-iap \
            --project=${PROJECT_ID} \
            --zone=asia-northeast1-a \
            --quiet \
            --command="sudo apt-get update && sudo apt-get install -y postgresql-client" && {
              echo "PostgreSQL 客户端安装成功！"
              break
            } || {
              echo "等待 VM 或 IAP 隧道就绪... ($i/10)"
              sleep 10
            }
        done
      else
        echo "NAT 未开启，跳过安装步骤。"
      fi
      
timeout: 1800s
