# 文件名: cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1. Terraform 初期化 (Init)
# -chdir 选项将工作目录切换到 environments/${_ENV_NAME}
- name: 'hashicorp/terraform:latest'
  id: 'Terraform Init'
  args:
    - '-chdir=environments/${_ENV_NAME}' # 切换到环境目录
    - 'init'
    - '-backend-config=bucket=${_TF_STATE_BUCKET}'
    - '-backend-config=prefix=${_ENV_NAME}'

# 2. Terraform 構文検証 (Validate)
- name: 'hashicorp/terraform:latest'
  id: 'Terraform Validate'
  args:
    - '-chdir=environments/${_ENV_NAME}' # 切换到环境目录
    - 'validate'

# 3. Terraform プラン (Plan) - 将 plan 文件保存在工作区根目录
- name: 'hashicorp/terraform:latest'
  id: 'Terraform Plan'
  args:
    - '-chdir=environments/${_ENV_NAME}' # 切换到环境目录
    - 'plan'
    - '-out=/workspace/tfplan' # 注意：Plan 文件保存在 Cloud Build 工作区的根目录
    - '-input=false'

# 4. Terraform 適用 (Apply)
- name: 'hashicorp/terraform:latest'
  id: 'Terraform Apply'
  args:
    - '-chdir=environments/${_ENV_NAME}' # 切换到环境目录
    - 'apply'
    - '-auto-approve'
    - '/workspace/tfplan' # 应用保存在工作区根目录的 plan 文件
timeout: 1800s

